version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - mynetwork

networks:
  mynetwork:
